name: "Manual Jenkins Trigger"


on:
  workflow_dispatch:
    inputs:
      PERSON_NAME:
        description: 'Hello world'
        required: true
        default: 'GitHub Button'

jobs:
 
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Jenkins Job"
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          
          job: "githubTest"
          
          parameters: |
            PERSON_NAME=${{ github.event.inputs.TEST }}
